name: Save Link
description: Publish a link, or start a new draft
title: "[Link Title]"
labels: ["link", "draft"]
body:
  - type: input
    id: url
    attributes:
      label: URL
      placeholder: https://example.com
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: Image
  - type: input
    id: via
    attributes:
      label: Via
