name: Link
description: Save Link
title: "[Link]"
labels: ["link"]
body:
  - type: input
  id: url
  attributes:
    label: URL
    placeholder: https://example.com
  validations:
    required: true
  - type: textarea
  id: description
  attributes:
    label: Description
  validations:
    required: true
