name: Link
description: Save Link
title: "[Link]"
labels: ["link"]
body:
  - type: input
    id: url
    attributes:
      label: URL
      placeholder: https://example.com
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags
      description: A comma-separated list of tags
  - type: input
    id: via
    attributes:
      label: Via
  - type: input
    id: image
    attributes:
      label: Image
      placeholder: Leave blank
