on:
  issues:
    types:
      - opened
      - edited

jobs:
  save_link:
    runs-on: ubuntu-latest
    name: Save Link
    if: contains( github.event.issue.labels.*.name, 'link') && github.event.issue.user.login == github.event.repository.owner.login
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save Link
        uses: ashur/issue-actions/actions/issue-link@v0.2.5
        id: save-link
        with:
          folder: "./src/_data/links"
          issue-template: "link.yml"
          hash-property-name: "url"

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *
          git commit -m "Adding data for #${{ env.IssueNumber }}"
          git push

      - name: Close issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: "${{ env.IssueNumber }}"
          comment: "Added data file for #${{ env.IssueNumber }}"
