on:
  issues:
    types:
      - opened
      - edited

jobs:
  save_link:
    runs-on: ubuntu-latest
    name: Save Link
    if: contains( github.event.issue.labels.*.name, 'link') && github.event.issue.user.login == github.event.repository.owner.login
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug
        uses: ashur/issue-actions/actions/debug@v0.1.6
        id: debug

      - name: Save Link
        uses: ashur/issue-actions/actions/issue-link@v0.1.2
        id: save-link
        with:
          folder: "./src/_data/links"
          issue-template: "link.yml"
          hash-property-name: "url"
